
server:
  port: 8083

spring:
  application:
    name: restaurant
  profiles:
    active: dev

  config:
    import: "optional:configserver:${CONFIG_SERVER_PATH:http://localhost:8888}"

  cloud:
    config:
      uri: ${CONFIG_SERVER_PATH:http://localhost:8888}

  jpa:
    hibernate:
      ddl-auto: update   # Or validate / create / none / create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect



management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,env
  metrics:
    export:
      prometheus:
        enabled: true
  prometheus:
    enabled: true





eureka:
  client:
    service-url:
      defaultZone: ${SERVICE_DISCOVERY_DEFAULT_ZONE:http://localhost:8761/eureka}

logging:
  level:
    com:
      microservices:
        restaurant: DEBUG
  pattern:
    level: "%5p [${spring.application.name}]"
  file:
    name: ${SPRING_BOOT_LOG_FILE:/var/log/restaurant-app.log}