spring:
  application:
    name: restaurant
  profiles:
    active: dev

  config:
    import: "optional:configserver:http://localhost:8888/"

  cloud:
    config:
      uri: http://localhost:8888

  jpa:
    hibernate:
      ddl-auto: update   # Or validate / create / none / create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
