
spring:
  config:
    import: "optional:configserver:http://localhost:8888"

  cloud:
    config:
      uri: ${CONFIG_SERVER_PATH:http://localhost:8888}

eureka:
  client:
    service-url:
      defaultZone: ${SERVICE_DISCOVERY_DEFAULT_ZONE:http://localhost:8761/eureka}
