spring:
  application:
    name: ${APPLICATION_NAME:gateway-application}
server:
  port: ${SERVER_PORT:7771}
eureka:
  client:
    service-url:
      defaultZone: ${SERVICE_DISCOVERY_DEFAULT_ZONE:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

