spring:
  application:
    name: ${APPLICATION_NAME:gateway-application}
server:
  port: ${SERVER_PORT:7771}
  address: 0.0.0.0
eureka:
  client:
    service-url:
      defaultZone: ${SERVICE_DISCOVERY_DEFAULT_ZONE:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always



springdoc:
  swagger-ui:
    urls:
      - url: /restaurant/v3/api-docs
        name: RESTAURANT Service
      - url: /payments/v3/api-docs
        name: PAYMENTS Service
      - url: /sales/v3/api-docs
        name: SALES Service

