spring:
  datasource:
    url: jdbc:postgresql://192.168.0.108:5432/restaurant
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
payment:
  service:
    url: ${GATE_WAY_URL:http://localhost:7771/payments}
sales:
  service:
    url: ${GATE_WAY_URL:http://localhost:7771/sales}