
server:
  port: ${SERVER_PORT:8888}

spring:
  application:
    name: ${APPLICATION_NAME:config-server}

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/
  profiles:
    active: native

eureka:
  client:
    service-url:
      defaultZone: ${SERVICE_DISCOVERY_DEFAULT_ZONE:http://localhost:8761/eureka}