#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: configuration-service
#  labels:
#    app: configuration-service
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: configuration-service
#  template:
#    metadata:
#      labels:
#        app: configuration-service
#    spec:
#      containers:
#        - name: configuration-service
#          image: configuration-server:latest
#          imagePullPolicy: IfNotPresent   # <-- Add this
#          ports:
#            - containerPort: 8888
#          env:
#            - name: APPLICATION_NAME
#              value: "configuration-service"
#            - name: SERVICE_DISCOVERY_DEFAULT_ZONE
#              value: "http://eurekaserver:8761/eureka"
#            - name: SERVER_PORT
#              value: "8888"
#            - name: SPRING_BOOT_LOG_FILE
#              value: "/var/log/configuration-app.log"
#          volumeMounts:
#            - name: logs-volume
#              mountPath: /var/log
#          readinessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8888
#            initialDelaySeconds: 10
#            periodSeconds: 20
#            timeoutSeconds: 5
#            failureThreshold: 10
#      volumes:
#        - name: logs-volume
#          emptyDir: {}
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: configuration-service
#spec:
#  selector:
#    app: configuration-service
#  ports:
#    - protocol: TCP
#      port: 8888
#      targetPort: 8888
#  type: ClusterIP


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service
  labels:
    app: restaurant-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-service
  template:
    metadata:
      labels:
        app: restaurant-service
    spec:
      containers:
        - name: restaurant
          image: restaurant:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090
          env:
            - name: APPLICATION_NAME
              value: "restaurant-service"
            - name: CONFIG_SERVER_PATH
              value: "http://configuration-service:8888"
            - name: SERVICE_DISCOVERY_DEFAULT_ZONE
              value: "http://eurekaserver:8761/eureka"
            - name: SERVER_PORT
              value: "8090"
            - name: SPRING_BOOT_LOG_FILE
              value: "/var/log/restaurant-app.log"
          volumeMounts:
            - name: log-volume
              mountPath: /var/log
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8090
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8090
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
        - name: log-volume
          emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  labels:
    app: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway
          image: app-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090
          env:
            - name: APPLICATION_NAME
              value: "app-restaurant-service"
#            - name: CONFIG_SERVER_PATH
#              value: "http://configuration-service:8888"
#            - name: SERVICE_DISCOVERY_DEFAULT_ZONE
#              value: "http://eurekaserver:8761/eureka"
            - name: SERVER_PORT
              value: "8090"
            - name: SPRING_BOOT_LOG_FILE
              value: "/var/log/restaurant-app.log"
          volumeMounts:
            - name: log-volume
              mountPath: /var/log
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8090
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8090
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
        - name: log-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
  labels:
    app: restaurant-service
spec:
  selector:
    app: restaurant-service
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    app: gateway-service
spec:
  selector:
    app: gateway-service
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: NodePort
